// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzD7bjKmVg6ZAl70X_uLv2KMpfZqFOv8g',
    appId: '1:109549606658:web:e5750ebf4187c49394d41b',
    messagingSenderId: '109549606658',
    projectId: 'pink-book-2a2b6',
    authDomain: 'pink-book-2a2b6.firebaseapp.com',
    storageBucket: 'pink-book-2a2b6.appspot.com',
    measurementId: 'G-RW93DP41NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_wh1jFHWZ7gaoYwR4vfcOkHxKl1Kn-zI',
    appId: '1:109549606658:android:2438316f7220b47494d41b',
    messagingSenderId: '109549606658',
    projectId: 'pink-book-2a2b6',
    storageBucket: 'pink-book-2a2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlDnXnk5Wrha7we_DFGLpu_EOE5OKHWQ',
    appId: '1:109549606658:ios:2590f842af5cf56894d41b',
    messagingSenderId: '109549606658',
    projectId: 'pink-book-2a2b6',
    storageBucket: 'pink-book-2a2b6.appspot.com',
    iosBundleId: 'com.example.pinkBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrlDnXnk5Wrha7we_DFGLpu_EOE5OKHWQ',
    appId: '1:109549606658:ios:2590f842af5cf56894d41b',
    messagingSenderId: '109549606658',
    projectId: 'pink-book-2a2b6',
    storageBucket: 'pink-book-2a2b6.appspot.com',
    iosBundleId: 'com.example.pinkBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzD7bjKmVg6ZAl70X_uLv2KMpfZqFOv8g',
    appId: '1:109549606658:web:2455eda52ed57e5494d41b',
    messagingSenderId: '109549606658',
    projectId: 'pink-book-2a2b6',
    authDomain: 'pink-book-2a2b6.firebaseapp.com',
    storageBucket: 'pink-book-2a2b6.appspot.com',
    measurementId: 'G-8TM6QXF9SD',
  );
}
